# Generated by Django 6.0.3 on 2026-03-15 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('location_id', models.IntegerField(help_text='Contoh: 4807', unique=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('zenwel_id', models.IntegerField(help_text='ID asli dari API Zenwel', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('zenwel_item_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('retail_price', models.FloatField()),
                ('is_addon', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('recency', models.FloatField()),
                ('frequency', models.FloatField()),
                ('monetary', models.FloatField()),
                ('length', models.FloatField()),
                ('age_months', models.FloatField()),
                ('cluster_id', models.IntegerField()),
                ('clv_score', models.FloatField()),
                ('simbol', models.CharField(max_length=10)),
                ('nama_grup', models.CharField(max_length=100)),
                ('is_churn', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='babyspa_data.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ref_number', models.CharField(help_text='Contoh: AS62M8QI', max_length=50, unique=True)),
                ('scheduled_date', models.DateTimeField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='babyspa_data.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='babyspa_data.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='babyspa_data.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='babyspa_data.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('cluster_id', models.IntegerField()),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
                ('rank_n', models.IntegerField()),
                ('antecedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_rules', to='babyspa_data.product')),
                ('consequent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_rules', to='babyspa_data.product')),
            ],
            options={
                'unique_together': {('cluster_id', 'antecedent', 'consequent')},
            },
        ),
    ]
