# Generated by Django 6.0.3 on 2026-03-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='status',
            field=models.CharField(default='COMPLETED', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='PAID', max_length=50),
        ),
    ]
