# Generated by Django 6.0.3 on 2026-03-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0002_transactionitem_status_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='ref_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
