# Generated by Django 6.0.3 on 2026-03-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0003_transactionitem_ref_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='conducted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
