# Generated by Django 6.0.3 on 2026-03-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0004_transactionitem_conducted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='conducted_date',
            new_name='scheduled_date',
        ),
    ]
