# Generated by Django 6.0.3 on 2026-03-18 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0005_rename_conducted_date_transactionitem_scheduled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHPConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(help_text='Contoh: Bobot Expert AHP 2024', max_length=100)),
                ('context', models.CharField(choices=[('LRFM', 'Customer Segmentation (LRFM)'), ('PRODUCT', 'Product Scoring (RFM/P)')], max_length=20)),
                ('w_length', models.FloatField(blank=True, default=0, help_text='Hanya untuk LRFM', null=True)),
                ('w_recency', models.FloatField()),
                ('w_frequency', models.FloatField()),
                ('w_monetary', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LRFMReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('symbol', models.CharField(help_text='Contoh: ↑↑↑↑', max_length=10, unique=True)),
                ('group_name', models.CharField(max_length=100)),
                ('main_category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='customersegment',
            name='age_months',
        ),
        migrations.RemoveField(
            model_name='customersegment',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='customersegment',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='customersegment',
            name='length',
        ),
        migrations.RemoveField(
            model_name='customersegment',
            name='monetary',
        ),
        migrations.RemoveField(
            model_name='customersegment',
            name='nama_grup',
        ),
        migrations.RemoveField(
            model_name='customersegment',
            name='recency',
        ),
        migrations.RemoveField(
            model_name='customersegment',
            name='simbol',
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='babyspa_data.customer'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='antecedent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_trigger', to='babyspa_data.product'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='consequent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_target', to='babyspa_data.product'),
        ),
        migrations.CreateModel(
            name='ClusterLRFM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('cluster_id', models.IntegerField(unique=True)),
                ('mean_length', models.FloatField()),
                ('mean_recency', models.FloatField()),
                ('mean_frequency', models.FloatField()),
                ('mean_monetary', models.FloatField()),
                ('ahp_config', models.ForeignKey(limit_choices_to={'context': 'LRFM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='babyspa_data.ahpconfiguration')),
                ('lrfm_reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='babyspa_data.lrfmreference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customersegment',
            name='cluster_lrfm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='babyspa_data.clusterlrfm'),
        ),
        migrations.CreateModel(
            name='ProductClusterScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('cluster_id', models.IntegerField()),
                ('total_saw_score', models.FloatField()),
                ('is_top_n', models.BooleanField(default=False)),
                ('ahp_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='babyspa_data.ahpconfiguration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyspa_data.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
