# Generated by Django 6.0.3 on 2026-03-18 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0006_ahpconfiguration_lrfmreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersegment',
            name='cluster_lrfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_segments', to='babyspa_data.clusterlrfm'),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segment', to='babyspa_data.customer'),
        ),
    ]
