# Generated by Django 6.0.3 on 2026-03-18 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0007_alter_customersegment_cluster_lrfm_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together={('antecedent', 'consequent')},
        ),
        migrations.CreateModel(
            name='ProductScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('r_normalized', models.FloatField(default=0)),
                ('f_normalized', models.FloatField(default=0)),
                ('m_normalized', models.FloatField(default=0)),
                ('total_saw_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('is_top_n', models.BooleanField(default=False)),
                ('ahp_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='babyspa_data.ahpconfiguration')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='babyspa_data.product')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.DeleteModel(
            name='ProductClusterScore',
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='cluster_id',
        ),
    ]
