# Generated by Django 6.0.3 on 2026-03-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0008_alter_productrecommendation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zenwel_id',
            new_name='erp_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='zenwel_item_id',
            new_name='erp_item_id',
        ),
    ]
