# Generated by Django 6.0.3 on 2026-03-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0009_rename_zenwel_id_customer_erp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.BooleanField(blank=True, help_text='True untuk laki-laki, False untuk perempuan, null jika tidak diketahui', null=True),
        ),
    ]
