# Generated by Django 6.0.3 on 2026-03-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0010_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
