# Generated by Django 6.0.3 on 2026-05-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0011_transactionitem_duration_transactionitem_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterlrfm',
            name='cluster_id',
            field=models.IntegerField(),
        ),
    ]
