# Generated by Django 6.0.3 on 2026-05-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0012_alter_clusterlrfm_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscore',
            name='cluster_id',
            field=models.ForeignKey(help_text='Cluster LRFM yang paling cocok untuk produk ini berdasarkan skor RFM_P-nya.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='babyspa_data.clusterlrfm'),
        ),
    ]
