# Generated by Django 6.0.3 on 2026-05-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0013_productscore_cluster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersegment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segment', to='babyspa_data.customer'),
        ),
    ]
