# Generated by Django 6.0.3 on 2026-05-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0014_alter_customersegment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterlrfm',
            name='k_value',
            field=models.IntegerField(blank=True, help_text='Nilai K yang digunakan saat pembentukan klaster ini.', null=True),
        ),
    ]
