# Generated by Django 6.0.3 on 2026-05-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0015_clusterlrfm_k_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscore',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='babyspa_data.product'),
        ),
    ]
