# Generated by Django 6.0.3 on 2026-05-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0016_alter_productscore_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterlrfm',
            name='max_discount_percent',
            field=models.FloatField(blank=True, default=0, help_text='Batas atas diskon (%)', null=True),
        ),
        migrations.AddField(
            model_name='clusterlrfm',
            name='min_discount_percent',
            field=models.FloatField(blank=True, default=0, help_text='Batas bawah diskon (%)', null=True),
        ),
    ]
