# Generated by Django 6.0.3 on 2026-05-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0017_clusterlrfm_max_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='cluster_lrfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babyspa_data.clusterlrfm'),
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='antecedent',
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='consequent',
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='antecedent',
            field=models.ManyToManyField(related_name='trigger', to='babyspa_data.product'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='consequent',
            field=models.ManyToManyField(related_name='target', to='babyspa_data.product'),
        ),
    ]
