# Generated by Django 6.0.3 on 2026-05-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0018_alter_productrecommendation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscore',
            name='f_real',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productscore',
            name='l_normalized',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productscore',
            name='l_real',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productscore',
            name='m_real',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productscore',
            name='r_real',
            field=models.FloatField(default=0),
        ),
    ]
