# Generated by Django 6.0.3 on 2026-05-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0019_productscore_f_real_productscore_l_normalized_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscore',
            name='f_real',
        ),
        migrations.RemoveField(
            model_name='productscore',
            name='l_normalized',
        ),
        migrations.RemoveField(
            model_name='productscore',
            name='l_real',
        ),
        migrations.RemoveField(
            model_name='productscore',
            name='m_real',
        ),
        migrations.RemoveField(
            model_name='productscore',
            name='r_real',
        ),
    ]
