# Generated by Django 6.0.3 on 2026-05-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0020_remove_productscore_f_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersegment',
            name='f_normalized',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='f_real',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='l_normalized',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='l_real',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='m_normalized',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='m_real',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='r_normalized',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='r_real',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clusterlrfm',
            name='mean_frequency',
            field=models.FloatField(help_text='Rata-rata Frequency (F) untuk klaster ini REAL.'),
        ),
        migrations.AlterField(
            model_name='clusterlrfm',
            name='mean_length',
            field=models.FloatField(help_text='Rata-rata Length (L) untuk klaster ini REAL.'),
        ),
        migrations.AlterField(
            model_name='clusterlrfm',
            name='mean_monetary',
            field=models.FloatField(help_text='Rata-rata Monetary (M) untuk klaster ini REAL.'),
        ),
        migrations.AlterField(
            model_name='clusterlrfm',
            name='mean_recency',
            field=models.FloatField(help_text='Rata-rata Recency (R) untuk klaster ini REAL.'),
        ),
    ]
