# Generated by Django 6.0.3 on 2026-05-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0021_customersegment_f_normalized_customersegment_f_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersegment',
            name='sage_month',
            field=models.FloatField(default=0),
        ),
    ]
