# Generated by Django 6.0.3 on 2026-05-16 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0022_customersegment_sage_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersegment',
            old_name='sage_month',
            new_name='age_month',
        ),
    ]
