# Generated by Django 6.0.3 on 2026-05-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0023_rename_sage_month_customersegment_age_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersegment',
            name='age_month',
        ),
    ]
