# Generated by Django 6.0.3 on 2026-05-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0024_remove_customersegment_age_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersegment',
            name='age',
            field=models.IntegerField(default=0, help_text='Usia bayi/anak dalam bulan, dihitung dari tanggal lahir dan transaksi terbaru'),
        ),
    ]
