# Generated by Django 6.0.3 on 2026-05-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0025_customersegment_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscore',
            name='name',
            field=models.CharField(blank=True, help_text='Nama produk untuk referensi cepat atau hasil similarity.', max_length=255, null=True),
        ),
    ]
