# Generated by Django 6.0.3 on 2026-05-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0026_productscore_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscore',
            name='name',
        ),
    ]
