# Generated by Django 6.0.3 on 2026-05-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0027_remove_productscore_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscore',
            name='name',
            field=models.CharField(blank=True, help_text="Nama unik untuk skor ini, misal 'Global' atau 'Cluster 1'", max_length=255, null=True),
        ),
    ]
