# Generated by Django 6.0.3 on 2026-05-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0028_productscore_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='master_product',
            field=models.ForeignKey(blank=True, help_text='Jika produk ini adalah varian berdasakan cabang, hubungkan ke produk utama. Jika tidak, biarkan kosong.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='babyspa_data.product'),
        ),
    ]
