# Generated by Django 6.0.3 on 2026-05-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0029_product_master_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi produk, bisa digunakan untuk analisis teks lebih lanjut, mungkin NLP.', null=True),
        ),
    ]
