# Generated by Django 6.0.3 on 2026-05-25 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0031_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Cabang tempat produk ini tersedia. Jika produk ini adalah varian khusus cabang, hubungkan ke cabang tersebut. Jika produk ini adalah produk utama yang tersedia di semua cabang, biarkan kosong.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_products', to='babyspa_data.branch'),
        ),
    ]
