# Generated by Django 6.0.3 on 2026-05-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0032_product_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Cabang-cabang tempat produk ini tersedia. Jika produk ini aktif di beberapa cabang sekaligus, pilih cabang terkait.', related_name='branch_products', to='babyspa_data.branch'),
        ),
    ]
