# Generated by Django 6.0.3 on 2026-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0033_remove_product_branch_product_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersegment',
            name='f_normalized',
            field=models.FloatField(default=0, help_text='Nilai F yang sudah ternormalisasi,  KEMUNGKINAN DEPRECATED'),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='f_real',
            field=models.FloatField(default=0, help_text='Jumlah total kunjungan,  KEMUNGKINAN DEPRECATED'),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='l_normalized',
            field=models.FloatField(default=0, help_text='Nilai L yang sudah ternormalisasi, siap untuk digunakan dalam algoritma clustering,  KEMUNGKINAN DEPRECATED'),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='l_real',
            field=models.FloatField(default=0, help_text='Durasi hubungan pelanggan (hari), dihitung dari tanggal transaksi pertama hingga terakhir). KEMUNGKINAN DEPRECATED'),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='m_normalized',
            field=models.FloatField(default=0, help_text='Nilai M yang sudah ternormalisasi,  KEMUNGKINAN DEPRECATEDs'),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='m_real',
            field=models.FloatField(default=0, help_text='Total pengeluaran pelanggan,  KEMUNGKINAN DEPRECATED'),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='r_normalized',
            field=models.FloatField(default=0, help_text='Nilai R yang sudah ternormalisasi,  KEMUNGKINAN DEPRECATED'),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='r_real',
            field=models.FloatField(default=0, help_text='Hari sejak kunjungan terakhir,  KEMUNGKINAN DEPRECATED'),
        ),
    ]
