# Generated by Django 6.0.3 on 2026-06-02 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0034_alter_customersegment_f_normalized_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('l_real', models.FloatField(default=0)),
                ('r_real', models.FloatField(default=0)),
                ('f_real', models.FloatField(default=0)),
                ('m_real', models.FloatField(default=0)),
                ('l_normalized', models.FloatField(default=0)),
                ('r_normalized', models.FloatField(default=0)),
                ('f_normalized', models.FloatField(default=0)),
                ('m_normalized', models.FloatField(default=0)),
                ('age', models.IntegerField(default=0, help_text='Usia bayi/anak dalam bulan saat skor dihitung')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_score', to='babyspa_data.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
