# Generated by Django 6.0.3 on 2026-06-02 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0035_customerscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerscore',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_score', to='babyspa_data.customer'),
        ),
    ]
