# Generated by Django 6.0.3 on 2026-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyspa_data', '0036_alter_customerscore_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Durasi dalam satuan menit', null=True),
        ),
    ]
